travis:
  secure:
    BINSTAR_TOKEN: fdp6AIUUwjD6oAGMRcTDvzv40MQUbNCM3zLAe1olqqqAguq/xqzCTT1KqC0yARiy8u1BG5CZAZXDdwXIq+UWuV4ta1B/fFHPe8wSwpPdoH9Z0OFQWm+P1jkHwf/zAEGZEEKJg4BYIPn9GaV+mWZDHF9CPmgvpvlC9AwI1sAH8HQ4OaZ1jLykTBdae+ZEVDrMwFQLmlihpTw0p1lWaldknd3pcK8IsdYJqHl093r5i7z/OGv7Y4zx0Wf5Yx0JygxWi/7whc3VbZTh2GTO+qThR8qnS5LKyYd3Vmc8TDEzt7aOmP0o3317kP8DIGOAYYUsfHD6hLih7LO2GhmcSDchiBPRTEAo6paZ9nmHyDxypp+gZZWsr/l84D9vFVeokE/ceU2scCuEa6RQBkApCmUw3GTstQyfetpaWF7WCfspZjPXpkNrVm4fGagh4okKP4EB/QIopfATrOUze2L6CCPwGb3ILurEmlYlzQ2+TfwopE3Tc9M4soXw5fp3RNHteWzjTj64gf6M1tsIjaBqBMHRUAzArIbpour7AwoKx/LWZIctJqRH3rIMZsmU+wAoSJY05cag19qOvp0+hg5oJO82gK0i/CUYfe+yORWUhPBHFNtuPLP0Jzb6Flz5R9bwud7pllH2Nxg7Wm1Zey8NksLsYXuwUFyC6Jf+XsRDyiVqRsc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
